module.exports = [
  {
    amountMaximum: 1000,
    amountMinimum: 1,
    isRefillable: false,
    isTerminatable: false,
    periodMaximum: 30,
    periodMinimum: 10,
    program: "base",
    rate: 90,
    terminationPenalty: 1,
  },
  {
    amountMaximum: 1000,
    amountMinimum: 1,
    isRefillable: false,
    isTerminatable: true,
    periodMaximum: 30,
    periodMinimum: 10,
    program: "nonrefillable",
    rate: 90,
    terminationPenalty: 1,
  },
  {
    amountMaximum: 1000,
    amountMinimum: 1,
    isRefillable: true,
    isTerminatable: false,
    periodMaximum: 30,
    periodMinimum: 10,
    program: "refillable",
    rate: 90,
    terminationPenalty: 1,
  },
  {
    amountMaximum: 1000,
    amountMinimum: 1,
    isRefillable: true,
    isTerminatable: true,
    periodMaximum: 30,
    periodMinimum: 10,
    program: "terminatable",
    rate: 90,
    terminationPenalty: 1,
  },
];
