module.exports = [
  {
    amountMaximum: 100,
    amountMinimum: 1,
    isRefillable: false,
    isTerminatable: false,
    periodMaximum: 30,
    periodMinimum: 10,
    program: "base",
    rate: 60,
    terminationPenalty: 1,
  },
  {
    amountMaximum: 200,
    amountMinimum: 50,
    isRefillable: false,
    isTerminatable: true,
    periodMaximum: 60,
    periodMinimum: 30,
    program: "nonrefillable",
    rate: 90,
    terminationPenalty: 1,
  },
  {
    amountMaximum: 500,
    amountMinimum: 100,
    isRefillable: true,
    isTerminatable: false,
    periodMaximum: 100,
    periodMinimum: 50,
    program: "refillable",
    rate: 120,
    terminationPenalty: 1,
  },
  {
    amountMaximum: 1000,
    amountMinimum: 200,
    isRefillable: true,
    isTerminatable: true,
    periodMaximum: 300,
    periodMinimum: 100,
    program: "terminatable",
    rate: 180,
    terminationPenalty: 1,
  },
];
